[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "aeronomy-app"

[services.build]
buildCommand = "npm run railway:build"

[services.deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[[services.variables]]
name = "NODE_ENV"
value = "production"

[[services.variables]]
name = "PORT"
value = "${{ PORT }}" 